### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u2026' in position 50: ordinal not in range(128)

### ISSUE THREAD

**Issue by AdamSutch** [politeauthority/docker-pretty-ps#22]
Seems unicode isn't supported.
I'm not a python dev but I might be able to take a stab at fixing this later in the week if you don't get to it.

```[02:01 PM] ~/docker-pretty-ps λ docker-pretty-ps
All currently running docker containers

pdf
	Container ID:         6e14d01f2b4d
	Image:                root_pdf
	Command:              yarn start
	Created:              2 hours ago
	Status:               Up 2 hours (healthy)
	Ports:                0.0.0.0:8402->8402/tcp

traefik
	Container ID:         05fa80172f3e
	Image:                helpers_traefik
Traceback (most recent call last):
  File "/usr/local/bin/docker-pretty-ps", line 4, in <module>
    __import__('pkg_resources').run_script('docker-pretty-ps==1.0.1', 'docker-pretty-ps')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/docker_pretty_ps-1.0.1-py3.5.egg/EGG-INFO/scripts/docker-pretty-ps", line 5, in <module>
    dockerprettyps.run_cli()
  File "/usr/local/lib/python3.5/dist-packages/docker_pretty_ps-1.0.1-py3.5.egg/dockerprettyps/__init__.py", line 84, in run_cli
    args)
  File "/usr/local/lib/python3.5/dist-packages/docker_pretty_ps-1.0.1-py3.5.egg/dockerprettyps/__init__.py", line 488, in print_format
    pretty_print_fmt_containers(containers, args)
  File "/usr/local/lib/python3.5/dist-packages/docker_pretty_ps-1.0.1-py3.5.egg/dockerprettyps/__init__.py", line 565, in pretty_print_fmt_containers
    print_data(print_content)
  File "/usr/local/lib/python3.5/dist-packages/docker_pretty_ps-1.0.1-py3.5.egg/dockerprettyps/__init__.py", line 730, in print_data
    print("%s %s" % (row[0].ljust(col_width), row[1]))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2026' in position 50: ordinal not in range(128)```

**Comment by politeauthority** [comment]
Could you add a copy of what docker ps is saying? I'll see if I can patch this tonight.
Thanks for the input!

**Comment by AdamSutch** [comment]
I'm mostly sure it's the `…` character (based on looking up the `\u2026`

```
05fa80172f3e        helpers_traefik                "/entrypoint.sh trae…"   8 weeks ago         Up 10 days             0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8490->8080/tcp   traefik
```

**Comment by AdamSutch** [comment]
Turns out the issue was with the docker container I was running this in. I didn't have the proper locales installed. Fixed it by adding the following to my dockerfile.
```
RUN apt-get install -y locales locales-all
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
```
