### ISSUE TITLE
Bug with containers 'Restarting'

### ISSUE THREAD

**Issue by politeauthority** [politeauthority/docker-pretty-ps#3]
When a container is 'Restarting' it crashes the get_container_time() method.
```
Traceback (most recent call last):
  File "/root/bin/docker-pretty-ps", line 239, in <module>
    run()
  File "/root/bin/docker-pretty-ps", line 39, in run
    containers = clean_output(stdout)
  File "/root/bin/docker-pretty-ps", line 85, in clean_output
    'staus_date': get_container_time(revised_line_split[4].strip())
  File "/root/bin/docker-pretty-ps", line 114, in get_container_time
    digit = int(digit)
ValueError: invalid literal for int() with base 10: 'restarting (1) 20 ago'
```

**Comment by politeauthority** [comment]
Fixed by PR #4
